sudo: false
language: java
jdk: oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_797cb90a1492_key -iv $encrypted_797cb90a1492_iv
  -in e55a2abaa177.json.enc -out e55a2abaa177.json -d
- mvn install -B -V
- chmod a+x mvnw

script:
- mvn clean install

before_deploy:
- cp target/calculatorProject*.war calculatorProject.war

deploy:
  provider: gae
  file: calculatorProject.war
  verbosity: debug
  keyfile: e55a2abaa177.json
  project: dotted-byway-229018
  default: true
  skip_cleanup: true
  on:
    branch: devel
