sudo: false
language: java
jdk: oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_797cb90a1492_key -iv $encrypted_797cb90a1492_iv
  -in e55a2abaa177.json.enc -out e55a2abaa177.json -d
- chmod a+x mvnw
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- "mvn clean install"

before_deploy:
- cp target/calculatorProject*.war target/calculatorProject.war

deploy:
  provider: gae
  file: target/calculatorProject-0.0.1-SNAPSHOT.war
  skip_cleanup: true
  keyfile: e55a2abaa177.json
  project: dotted-byway-229018
  default: true
  on:
    branch: devel
