sudo: false
language: java
jdk: oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_797cb90a1492_key -iv $encrypted_797cb90a1492_iv
  -in e55a2abaa177.json.enc -out e55a2abaa177.json -d
- mvn install -B -V
- chmod a+x mvnw

script:
- mvn clean install

before_deploy:
- mkdir -p key_file
- cp target/calculatorProject*.war calculatorProject-0.0.1.war 
- rm -rf target/
- mv e55a2abaa177.json key_file/  
 
deploy:
  provider: gae
  verbosity: debug
  keyfile: key_file/e55a2abaa177.json
  project: dotted-byway-229018
  default: true
  skip_cleanup: true
  on:
    branch: devel
