sudo: true
language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
- openssl aes-256-cbc -K $encrypted_797cb90a1492_key -iv $encrypted_797cb90a1492_iv
  -in e55a2abaa177.json.enc -out e55a2abaa177.json -d
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- sudo apt-get install google-cloud-sdk-app-engine-java
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file e55a2abaa177.json
#- gcloud components install app-engine-java
# [END auth]
- mvn install -B -V
- chmod a+x mvnw

install:
# Set the correct project to deploy to
- gcloud config set project dotted-byway-229018
# Install the Python dependencies

script:
# [START deploy]
- gcloud components install app-engine-java
- gcloud -q components update app-engine-java
# Deploy the app
- mvn appengine:deploy
# Run and end to end test
on:
    branch: devel
# [END deploy]