sudo: false
language: java
jdk: oraclejdk8


before_install:
- openssl aes-256-cbc -K $encrypted_b53eabcc89d8_key -iv $encrypted_b53eabcc89d8_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz

script:
- ./mvnw clean install -B

deploy:
    provider: gae
    skip_cleanup: true
    keyfile: e5a6d2d5a5ce.json
    project: dotted-byway-229018
    default: true
    on:
        all_branches: true

